# Generated by Django 4.0.1 on 2022-01-12 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('car_id', models.SlugField(unique=True, verbose_name='Slug de la voiture')),
                ('customer_need', models.CharField(max_length=200, verbose_name='Besoin du client')),
                ('car_title', models.CharField(max_length=200, verbose_name='Marque de la voiture')),
                ('city', models.CharField(max_length=200, verbose_name='Ville ')),
                ('area', models.CharField(max_length=200, verbose_name='Quartier')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True, verbose_name='ID Client')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name="Date d'envoi")),
            ],
        ),
    ]
