# Generated by Django 4.0.1 on 2022-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='car_id',
            field=models.SlugField(verbose_name='Slug de la voiture'),
        ),
    ]
