# Generated by Django 4.0.1 on 2022-01-17 09:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='image/about')),
                ('image2', models.ImageField(upload_to='image/about')),
                ('image3', models.ImageField(upload_to='image/about')),
                ('image11', models.ImageField(upload_to='image/about')),
                ('image22', models.ImageField(upload_to='image/about')),
                ('image33', models.ImageField(upload_to='image/about')),
                ('title', tinymce.models.HTMLField(verbose_name='Titre')),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'A propos',
            },
        ),
    ]
