# Generated by Django 4.0.1 on 2022-01-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=200, verbose_name='Prenom')),
                ('designation', models.CharField(max_length=200, verbose_name='Fonction')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('facebook_link', models.URLField(verbose_name='Lien Facebook')),
                ('twitter_link', models.URLField(verbose_name='Lien Twitter')),
                ('google_link', models.URLField(verbose_name='Lien Google')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Equipe Technique',
                'verbose_name_plural': 'Equipes Techniques',
            },
        ),
    ]
