# Generated by Django 4.0.1 on 2022-01-12 11:21

import datetime
from django.db import migrations, models
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', tinymce.models.HTMLField(verbose_name='Titre')),
                ('content', tinymce.models.HTMLField(verbose_name='Contenu')),
                ('image', models.ImageField(upload_to='media/banniere')),
            ],
            options={
                'verbose_name': 'Bannière',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=200, verbose_name='Nom de la voiture')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=200, verbose_name='Etat')),
                ('city', models.CharField(max_length=200, verbose_name='Ville')),
                ('color', models.CharField(choices=[('Azur clair', 'Azur clair'), ('Bleu clair', 'Bleu clair'), ('Bleu charron', 'Bleu charron'), ('Bleu sarcelle', 'Bleu sarcelle'), ('Bleu canard', 'Bleu canard'), ('Bleu fumée', 'Bleu fumée'), ('Lavande', 'Lavande'), ('Givré', 'Givré'), ('Pastel', 'Pastel'), ('Cerise', 'Cerise'), ('Lie de vin', 'Lie de vin'), ('Indigo', 'Indigo'), ('Pourpre', 'Pourpre'), ('Prune', 'Prune'), ('Violet', 'Violet'), ('Rouge-violet', 'Rouge-violet'), ('Magnata foncé', 'Magnata foncé'), ('Aubergine', 'Aubergine'), ('Pêche', 'Pêche'), ('Rose thé', 'Rose thé'), ('Framboise', 'Framboise'), ('Rose', 'Rose'), ('Saumon', 'Saumon'), ('Cerise', 'Cerise'), ('Mauve', 'Mauve'), ('Framboise', 'Framboise'), ('Bisque', 'Bisque'), ('Rouge bordeaux', 'Rouge bordeaux'), ('Rouge corail', 'Rouge corail'), ('Rouge granat', 'Rouge granat'), ('Rouge bismark', 'Rouge bismark'), ('Rouge alizarine', 'Rouge alizarine'), ('Rouge bourgogne', 'Rouge bourgogne'), ('Rouge vif', 'Rouge vif'), ('Rouge cerise', 'Rouge cerise'), ('Aurore', 'Aurore'), ('Carotte', 'Carotte'), ('Citrouille', 'Citrouille'), ('Melon', 'Melon'), ('Orange brûlée', 'Orange brûlée'), ('Mandarine', 'Mandarine'), ('Safran', 'Safran'), ('Vanille', 'Vanille'), ('Orangé', 'Orangé'), ('Ambre', 'Ambre'), ('Blond', 'Blond'), ('Citron', 'Citron'), ('Fauve', 'Fauve'), ('Or', 'Or'), ('Orpiment', 'Orpiment'), ('Soufre', 'Soufre'), ('Orc jaune', 'Orc jaune'), ('Asperge', 'Asperge'), ('Bleu sarcelle', 'Bleu sarcelle'), ('Bleu canard', 'Bleu canard'), ('Vert épinard', 'Vert épinard'), ('Vert olive', 'Vert olive'), ('Vert sapin', 'Vert sapin'), ('Vert kaki', 'Vert kaki'), ('Vert militaire', 'Vert militaire'), ('Vert pomme', 'Vert pomme'), ('Vert veronese', 'Vert veronese'), ('Vert pin', 'Vert pin'), ('Brou de noix', 'Brou de noix'), ('Noir charbon', 'Noir charbon'), ('Ebène', 'Ebène'), ("Noir d'encre", "Noir d'encre"), ('Dorian', 'Dorian'), ('Noiraud', 'Noiraud'), ('Cassis', 'Cassis'), ('Brun', 'Brun'), ('Acajou', 'Acajou'), ('Alezan', 'Alezan'), ('Auburn', 'Auburn'), ('Beige', 'Beige'), ('Beige clair', 'Beige clair'), ('Beigeasse', 'Beigeasse'), ('Bronze', 'Bronze'), ('Châtin', 'Châtin'), ('Chaudron', 'Chaudron'), ('Sang de boeuf', 'Sang de boeuf'), ('Marron', 'Marron'), ('Caramelle', 'Caramelle'), ('Basané', 'Basané'), ('Gris', 'Gris'), ('Ardoise', 'Ardoise'), ('Argent', 'Argent'), ('Celadon', 'Celadon'), ('Bitume', 'Bitume'), ('Gris perle', 'Gris perle'), ('Etain pur', 'Etain pur'), ('Tourdille', 'Tourdille'), ('Gris souris', 'Gris souris'), ('Albâtre', 'Albâtre'), ('Azur brume', 'Azur brume'), ('Blanc de lait', 'Blanc de lait'), ('Blanche', 'Blanche'), ('Blanc crème', 'Blanc crème'), ('Blanc neige', 'Blanc neige')], max_length=200, verbose_name='Couleur Exterieure')),
                ('modele', models.CharField(max_length=200, verbose_name='Modèle')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='Année')),
                ('condition', models.CharField(max_length=200, verbose_name='Condition')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('Contrôle de vitesse', 'Contrôle de vitesse'), ('Interface audio', 'Interface audio'), ('Airbags', 'Airbags'), ('Air Conditionné', 'Air Conditionné'), ('Chauffage des sièges', 'Chauffage des sièges'), ("Systeme d'alarme", "Systeme d'alarme"), ('Systeme de parking', 'Systeme de parking'), ('Direction assistée', 'Direction assistée'), ('Camera de recul', 'Camera de recul'), ('Injection de caburant', 'Injection de caburant'), ('Auto demarrage/arrêt', 'Auto demarrage/arrêt'), ('Deflecteur', 'Deflecteur'), ('Assistant Bluetooth', 'Assistant Bluetooth')], max_length=5000, verbose_name='Fonctionnalités')),
                ('body_style', models.CharField(choices=[('Berline', 'Berline'), ('Coupé', 'Coupé'), ('Hayon', 'Hayon'), ('Break', 'Break'), ('Limousine', 'Limousine'), ('Pick Up', 'Pick Up'), ('Crossovers', 'Crossovers'), ('SUV', 'SUV'), ('Fourgonnette', 'Fourgonnette'), ('Minivan', 'Minivan'), ('Liftback', 'Liftback'), ('Cabriolet', 'Cabriolet'), ('Minibus', 'Minibus'), ('Roadsters', 'Roadsters'), ('Targa', 'Targa'), ('4X4', '4X4'), ('Monospace', 'Monospace')], max_length=200, verbose_name='Type de Vehicule')),
                ('engine', models.CharField(max_length=200, verbose_name='Moteur')),
                ('transmission', models.CharField(max_length=200)),
                ('gearbox', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], default='Manuelle', max_length=200, verbose_name='Boîte de vitesse')),
                ('interior', models.CharField(max_length=200, verbose_name='Decoration interieure')),
                ('milage', models.IntegerField(verbose_name='Kilometrage')),
                ('miles', models.IntegerField(verbose_name='Km')),
                ('doors', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2, verbose_name='Portière')),
                ('passengers', models.IntegerField(verbose_name='Passagers')),
                ('vin_no', models.CharField(default='N/A', max_length=200, verbose_name='Immatriculation')),
                ('fuel', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Electrique')], max_length=200, verbose_name='Carburant')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Voiture vedette')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('image1', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('image4', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
                ('for_sale', models.BooleanField(default=False, verbose_name='A vendre ?')),
                ('no_of_owners', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Vehicule',
                'verbose_name_plural': 'Vehicules',
            },
        ),
    ]
