# Generated by Django 4.0.1 on 2022-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Occasion', 'Occasion'), ('Neuve', 'Neuve')], max_length=200, verbose_name='Condition'),
        ),
    ]
