# Generated by Django 4.0.1 on 2022-01-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(verbose_name='Lien Facebook')),
                ('twitter_link', models.URLField(verbose_name='Lien Twitter')),
                ('instagram_link', models.URLField(verbose_name='Lien Instagram')),
                ('linkedin_link', models.URLField(verbose_name='Lien linkedin')),
            ],
            options={
                'verbose_name_plural': 'Liens de medias sociaux',
            },
        ),
    ]
